/**
 * RFC 5545 iCalendar (.ics) generator for IRS PPS scheduled call invites.
 *
 * Why universal .ics + email instead of Google Calendar OAuth:
 *   - Works on every calendar app (Google Calendar, Outlook, Apple Calendar,
 *     Yahoo, Fastmail, etc.) without requiring expert OAuth flow.
 *   - Zero server-side calendar credentials to manage.
 *   - Expert receives an email — Gmail / Outlook auto-detect it as a meeting
 *     invite and surface "Yes / Maybe / No" RSVP buttons inline. Accepting
 *     puts it on their primary calendar exactly as a Google Calendar event
 *     would.
 *
 * Supported methods (RFC 5546):
 *   REQUEST  — new invite (call scheduled)
 *   CANCEL   — call canceled (sent on cancel/reassign)
 *   REPLY    — not generated by us; experts' RSVPs flow through their email
 *              client back to ModernTax via the ATTENDEE address
 *
 * Reschedule pattern: send a fresh REQUEST with the same UID + SEQUENCE
 * incremented by 1. Calendar clients treat this as an update to the existing
 * event rather than a duplicate.
 */

export interface CalendarInviteInput {
  /** Stable identifier for this event. Same UID across REQUEST/CANCEL/UPDATE
   *  for the same call session. Format: irs-call-{sessionId}@moderntax.io */
  uid: string;
  /** Increment when sending an update for an existing UID. 0 for first send. */
  sequence?: number;
  /** Method controls how the calendar client interprets the file. */
  method: 'REQUEST' | 'CANCEL';
  /** When the call fires (ISO timestamp). */
  startsAt: Date;
  /** Estimated end time. IRS PPS calls run 30-90 min — we use 60 min default. */
  endsAt: Date;
  /** Visible title on the expert's calendar. */
  summary: string;
  /** Long-form details — agenda, entity list, what to do, links. */
  description: string;
  /** Phone-number string for LOCATION (so the calendar shows a "where to call"). */
  location?: string;
  /** ModernTax sender — the SendGrid sender email + name. */
  organizer: { email: string; name: string };
  /** The expert receiving the invite. */
  attendee: { email: string; name?: string };
  /** Optional URL surfaced in the description (link back to the call console). */
  url?: string;
}

/**
 * Format a Date as an RFC 5545 UTC datetime: YYYYMMDDTHHMMSSZ.
 * No dashes, no colons, trailing Z. Calendar clients are picky about this.
 */
function formatIcsDate(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return (
    d.getUTCFullYear().toString() +
    pad(d.getUTCMonth() + 1) +
    pad(d.getUTCDate()) +
    'T' +
    pad(d.getUTCHours()) +
    pad(d.getUTCMinutes()) +
    pad(d.getUTCSeconds()) +
    'Z'
  );
}

/**
 * Escape per RFC 5545 §3.3.11. Required for SUMMARY, DESCRIPTION, LOCATION
 * field VALUEs. Order matters: backslash first, then the others.
 */
function escapeText(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

/**
 * Fold a single content line at 75 octets per RFC 5545 §3.1. Long lines must
 * be split with CRLF + a single space; missing this trips Outlook (Gmail is
 * more forgiving). We treat the input as ASCII for length purposes — anything
 * non-ASCII in our payload is escaped via escapeText already.
 */
function foldLine(line: string): string {
  if (line.length <= 75) return line;
  const chunks: string[] = [];
  let i = 0;
  while (i < line.length) {
    const take = i === 0 ? 75 : 74; // continuation lines get a leading space
    chunks.push((i === 0 ? '' : ' ') + line.slice(i, i + take));
    i += take;
  }
  return chunks.join('\r\n');
}

/**
 * Build the .ics body. Output uses CRLF line endings (RFC 5545 mandates them
 * and Outlook silently rejects LF-only files).
 */
export function buildIcsInvite(input: CalendarInviteInput): string {
  const now = new Date();
  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//ModernTax//IRS PPS Call Scheduler//EN',
    'CALSCALE:GREGORIAN',
    `METHOD:${input.method}`,
    'BEGIN:VEVENT',
    `UID:${input.uid}`,
    `SEQUENCE:${input.sequence ?? 0}`,
    `DTSTAMP:${formatIcsDate(now)}`,
    `DTSTART:${formatIcsDate(input.startsAt)}`,
    `DTEND:${formatIcsDate(input.endsAt)}`,
    `SUMMARY:${escapeText(input.summary)}`,
    `DESCRIPTION:${escapeText(input.description)}`,
  ];
  if (input.location) lines.push(`LOCATION:${escapeText(input.location)}`);
  if (input.url) lines.push(`URL:${input.url}`);

  // ORGANIZER — the inviter. Calendar clients display this as "From".
  lines.push(`ORGANIZER;CN=${escapeText(input.organizer.name)}:mailto:${input.organizer.email}`);

  // ATTENDEE — the expert. RSVP=TRUE asks for accept/decline. PARTSTAT=NEEDS-ACTION
  // makes Gmail/Outlook show the inline RSVP buttons.
  const attendeeParams = [
    'CUTYPE=INDIVIDUAL',
    'ROLE=REQ-PARTICIPANT',
    'PARTSTAT=NEEDS-ACTION',
    'RSVP=TRUE',
  ];
  if (input.attendee.name) attendeeParams.push(`CN=${escapeText(input.attendee.name)}`);
  lines.push(`ATTENDEE;${attendeeParams.join(';')}:mailto:${input.attendee.email}`);

  if (input.method === 'CANCEL') {
    // Cancellation requires STATUS:CANCELLED on the VEVENT for clients to
    // honor it (otherwise Outlook may keep the event as TENTATIVE).
    lines.push('STATUS:CANCELLED');
  } else {
    // Default reminders: 15 min and 5 min before. Two VALARMs are fine; the
    // expert's calendar will dedupe if they have system defaults.
    lines.push(
      'BEGIN:VALARM',
      'ACTION:DISPLAY',
      'DESCRIPTION:IRS PPS call in 15 minutes',
      'TRIGGER:-PT15M',
      'END:VALARM',
      'BEGIN:VALARM',
      'ACTION:DISPLAY',
      'DESCRIPTION:IRS PPS call in 5 minutes',
      'TRIGGER:-PT5M',
      'END:VALARM',
    );
  }

  lines.push('END:VEVENT', 'END:VCALENDAR');

  // Apply line folding to each content line, then join with CRLF.
  return lines.map(foldLine).join('\r\n');
}

/**
 * Stable UID for a call session. Same UID across the lifecycle so a
 * reschedule (METHOD:REQUEST with sequence+1) updates the existing event
 * rather than creating a duplicate.
 */
export function callSessionUid(callSessionId: string): string {
  return `irs-call-${callSessionId}@moderntax.io`;
}
