/**
 * Shared "send an 8821 with HelloSign-blocked fallback" helper.
 *
 * Tries Dropbox Sign first. If the SDK returns 402 payment_required
 * (free-tier signed-API blocked, as of 2026-05-13 still in negotiation
 * with HelloSign sales), falls through to generating the 8821 PDF
 * locally and emailing it to the signer via SendGrid with print/sign/
 * email-back instructions. Stamps signature_id either with the real
 * Dropbox Sign id or `MANUAL-<entity-id-short>` so downstream code
 * can tell which path was used.
 *
 * Used by:
 *   • app/api/upload/csv/route.ts          — inline on each entity insert
 *   • app/api/cron/8821-auto-send-pending  — daily sweep for stragglers
 *   • scripts/fire-stuck-8821s.ts          — one-shot recovery
 *
 * Idempotent on the entity row — call it once. If sending fails entirely
 * (both HelloSign 402 AND SendGrid error), the row stays at status=pending
 * and the daily cron retries.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { sendSignatureRequest } from './dropbox-sign';
import { send8821ManualSignatureEmail } from './sendgrid';
import { generate8821PDF, DESIGNEES } from './8821-pdf';

export interface SendCandidate {
  id: string;
  entity_name: string;
  form_type: string | null;
  tid: string | null;
  tid_kind: string | null;
  signer_email: string;
  signer_first_name: string | null;
  signer_last_name: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip_code: string | null;
  request_id?: string;
}

export interface SendResult {
  outcome: 'sent_hellosign' | 'sent_manual' | 'failed';
  signature_id?: string;
  /** Set when outcome='failed'. */
  error?: string;
}

export async function send8821WithFallback(
  entity: SendCandidate,
  admin: SupabaseClient,
): Promise<SendResult> {
  // --- 1. Try Dropbox Sign first ---
  try {
    const sig = await sendSignatureRequest(
      {
        id: entity.id,
        entity_name: entity.entity_name,
        form_type: entity.form_type || '1040',
        tid: entity.tid || undefined,
        tid_kind: entity.tid_kind || undefined,
        signer_first_name: entity.signer_first_name,
        signer_last_name: entity.signer_last_name,
        address: entity.address || undefined,
        city: entity.city || undefined,
        state: entity.state || undefined,
        zip_code: entity.zip_code || undefined,
      },
      entity.signer_email,
    );
    await admin
      .from('request_entities')
      .update({
        signature_id: sig.signatureRequestId,
        status: '8821_sent',
        signature_created_at: new Date().toISOString(),
      })
      .eq('id', entity.id);
    return { outcome: 'sent_hellosign', signature_id: sig.signatureRequestId };
  } catch (err: any) {
    const isPaymentRequired = err?.statusCode === 402 || /payment_required/i.test(JSON.stringify(err?.body || ''));
    if (!isPaymentRequired) {
      console.error(`[send-8821-with-fallback] non-402 error for ${entity.entity_name}:`, err.message);
      return { outcome: 'failed', error: err.message?.slice(0, 500) || 'unknown HelloSign error' };
    }
    // 402 — fall through to manual path below.
  }

  // --- 2. Fallback: generate PDF + email via SendGrid ---
  try {
    const formType = (entity.form_type || '1040') as '1040' | '1065' | '1120' | '1120S';
    const designee = Object.values(DESIGNEES)[0];
    const address = [entity.address, entity.city, entity.state, entity.zip_code]
      .filter(Boolean)
      .join(', ');
    const pdfBytes = await generate8821PDF({
      taxpayer: { name: entity.entity_name || '', tin: entity.tid || '', address },
      designee,
      formType,
    });
    const signerName = [entity.signer_first_name, entity.signer_last_name]
      .filter(Boolean)
      .join(' ') || entity.entity_name;
    await send8821ManualSignatureEmail({
      signerEmail: entity.signer_email,
      signerName,
      entityName: entity.entity_name,
      formType: entity.form_type || '',
      pdfBytes,
      entityId: entity.id,
    });
    const manualSigId = `MANUAL-${entity.id.slice(0, 8)}`;
    await admin
      .from('request_entities')
      .update({
        signature_id: manualSigId,
        status: '8821_sent',
        signature_created_at: new Date().toISOString(),
      })
      .eq('id', entity.id);
    return { outcome: 'sent_manual', signature_id: manualSigId };
  } catch (fbErr: any) {
    console.error(`[send-8821-with-fallback] manual fallback failed for ${entity.entity_name}:`, fbErr.message);
    return {
      outcome: 'failed',
      error: `HelloSign 402 + manual fallback failed: ${fbErr.message?.slice(0, 300)}`,
    };
  }
}

/**
 * Returns true if the signature_id was generated by our manual-PDF
 * fallback rather than Dropbox Sign. Used by the reminder cron to
 * route correctly — MANUAL ids can't be reminded via Dropbox Sign's
 * sendReminder API and need a fresh PDF email instead.
 */
export function isManualSignatureId(signatureId: string | null | undefined): boolean {
  return !!signatureId && signatureId.startsWith('MANUAL-');
}
